name: MegaloSMPCore
version: '${project.version}'
main: com.alticator.megalosmp.megalosmpcore.Core
api-version: 1.19
authors: [ MegaloSMP ]
description: The core plugin for the MegaloSMP server.
website: https://github.com/MegaloSMP/MegaloSMP-Core
commands:
  exchange:
    aliases: x
    description: Buy or sell items.
    usage: "/<command> buy/sell ItemName [quantity (optional, default=1)]"
  exchangeprice:
    aliases: xprice
    description: Show price for items available through the /exchange command.
    usage: "/<command> ItemName [quantity (optional, default=1)]"
  ignite:
    description: Set another player (or yourself) on fire.
    usage: "/<command> PlayerName"
  pack:
    description: Buy a predefined pack or item.
    usage: "/<command> PackName"
  packprice:
    description: Check the price for a pack or item available from the /pack command.
    usage: "/<command> PackName"
